spring.application.name=monitoring

spring.ai.google.genai.api-key=${GEMINI_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash

#enabling actuator endpoints
management.endpoints.web.exposure.include=*
